FROM ubuntu:bionic AS builder
MAINTAINER kongroo <imjcqt@gmail.com>
WORKDIR /root

ARG CLANG_VERSION="5.0.1"
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y --no-install-recommends --no-install-suggests \
        ca-certificates \
        vim \
        git \
        curl \
        build-essential \
        cmake \
        python3-dev \
        golang \
        openjdk-8-jdk \
        mono-devel \
        rustc
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash \
    && export NVM_DIR="$HOME/.nvm" \
    && [ -s "$NVM_DIR/nvm.sh"  ] && \. "$NVM_DIR/nvm.sh" \
    && nvm install --lts \
    && git clone --depth=1 https://github.com/Valloric/YouCompleteMe /root/.vim/bundle/YouCompleteMe \
    && npm install -g typescript \
    && cd /root/.vim/bundle/YouCompleteMe \
    && git submodule update --init --recursive
    # && wget https://releases.llvm.org/${CLANG_VERSION}/clang+llvm-${CLANG_VERSION}-x86_64-linux-gnu-ubuntu-16.04.tar.xz -p ./third_party/ycmd/clang_archives \
Run export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh"  ] && \. "$NVM_DIR/nvm.sh" \
    && cd /root/.vim/bundle/YouCompleteMe \
    && apt install -y cargo \
    && python3 install.py --clang-completer --go-completer --js-completer --java-completer --cs-completer --rust-completer \
    && rm -rf ./.git \
    && rm -rf ./third_party/ycmd/clang_archives
    # && rm -rf ./third_party/ycmd/cpp/BoostParts 
    # && rm -rf ./third_party/ycmd/third_party/OmniSharpServer

FROM ubuntu:bionic
WORKDIR /root
COPY --from=builder /root/.vim /root/.vim


